### PR TITLE
Small edits: moved variables to metadata.yml to use in all output

### PR DESCRIPTION
**Pull request by davidverweij**
In the existing implementation the code for the custom front page for the `.pdf` and the HTML export was written separately (not using joint variables). I've made some small edits:

- moved the title, author, etc. to a `metadata.yml` file,
- moved the content of `01_title_page.md` to the `template.tex`
- removed redundant code in the .html and .tex templates
- rewrote those templates to use the variables in the `metadata.yml` file
- added an optional subtitle variable

The resulting pdf and HTML is identical - except for the addition of a subtitle.

### CODE REVIEW

**Comment by davidverweij** [comment]
Let me know if you want me to merge a new master into this PR, if you merge any of the other PR's - like #94 . Cheers!

**Comment by dendrondal** [comment]
I like the idea of splitting up the YAML. Would definitely wait for #94 to merge, just in case XNOS breaks something.

**Comment by tompollard** [comment]
Thanks @davidverweij, looks good! The pull request needs a rebase after #94 was merged. Would you like to do this, or shall I?

**Comment by davidverweij** [comment]
Apologies on the extreme delay! Holidays, deadlines and being new to rebasing caused me to put this down my to-do list. Either way, I did a rebase and ran the code to test - all seems good from my end.

**Comment by tompollard** [comment]
No apologies needed! Looks great, thanks for doing this :)

**Pull request merged**
